import type { Config } from 'tailwindcss';
import { StatePlugin, PartPlugin } from 'tailwindcss-plugin-custom-elements';
import TypographyPlugin from '@tailwindcss/typography';

export default {
  content: ['./app/**/{**,.client,.server}/**/*.{js,jsx,ts,tsx}'],
  theme: {
    fontSize: {
      '2xs': 'var(--sl-font-size-2x-small)',
      xs: 'var(--sl-font-size-x-small)',
      sm: 'var(--sl-font-size-small)',
      base: 'var(--sl-font-size-medium)',
      lg: 'var(--sl-font-size-large)',
      xl: 'var(--sl-font-size-x-large)',
      '2xl': 'var(--sl-font-size-2x-large)',
      '3xl': 'var(--sl-font-size-3x-large)',
      '4xl': 'var(--sl-font-size-4x-large)',
    },
    extend: {
      colors: {
        primary: {
          50: 'rgb(var(--primary-50))',
          100: 'rgb(var(--primary-100))',
          200: 'rgb(var(--primary-200))',
          300: 'rgb(var(--primary-300))',
          400: 'rgb(var(--primary-400))',
          500: 'rgb(var(--primary-500))',
          600: 'rgb(var(--primary-600))',
          700: 'rgb(var(--primary-700))',
          800: 'rgb(var(--primary-800))',
          900: 'rgb(var(--primary-900))',
          950: 'rgb(var(--primary-950))',
        },
        secondary: {
          50: 'rgb(var(--secondary-50))',
          100: 'rgb(var(--secondary-100))',
          200: 'rgb(var(--secondary-200))',
          300: 'rgb(var(--secondary-300))',
          400: 'rgb(var(--secondary-400))',
          500: 'rgb(var(--secondary-500))',
          600: 'rgb(var(--secondary-600))',
          700: 'rgb(var(--secondary-700))',
          800: 'rgb(var(--secondary-800))',
          900: 'rgb(var(--secondary-900))',
          950: 'rgb(var(--secondary-950))',
        },
        neutral: {
          0: 'rgb(var(--neutral-0))',
          50: 'rgb(var(--neutral-50))',
          100: 'rgb(var(--neutral-100))',
          200: 'rgb(var(--neutral-200))',
          300: 'rgb(var(--neutral-300))',
          400: 'rgb(var(--neutral-400))',
          500: 'rgb(var(--neutral-500))',
          600: 'rgb(var(--neutral-600))',
          700: 'rgb(var(--neutral-700))',
          800: 'rgb(var(--neutral-800))',
          1000: 'rgb(var(--neutral-1000))',
        },
        danger: {
          50: 'rgb(var(--danger-50))',
          100: 'rgb(var(--danger-100))',
          200: 'rgb(var(--danger-200))',
          300: 'rgb(var(--danger-300))',
          400: 'rgb(var(--danger-400))',
          500: 'rgb(var(--danger-500))',
          600: 'rgb(var(--danger-600))',
          700: 'rgb(var(--danger-700))',
          800: 'rgb(var(--danger-800))',
          900: 'rgb(var(--danger-900))',
          950: 'rgb(var(--danger-950))',
        },
        'accent-primary': {
          50: 'rgb(var(--accent-primary-50))',
          100: 'rgb(var(--accent-primary-100))',
          200: 'rgb(var(--accent-primary-200))',
          300: 'rgb(var(--accent-primary-300))',
          400: 'rgb(var(--accent-primary-400))',
          500: 'rgb(var(--accent-primary-500))',
          600: 'rgb(var(--accent-primary-600))',
          700: 'rgb(var(--accent-primary-700))',
          800: 'rgb(var(--accent-primary-800))',
          900: 'rgb(var(--accent-primary-900))',
          950: 'rgb(var(--accent-primary-950))',
        },
        'accent-secondary': {
          50: 'rgb(var(--accent-secondary-50))',
          100: 'rgb(var(--accent-secondary-100))',
          200: 'rgb(var(--accent-secondary-200))',
          300: 'rgb(var(--accent-secondary-300))',
          400: 'rgb(var(--accent-secondary-400))',
        },
        'accent-tertiary': {
          50: 'rgb(var(--accent-tertiary-50))',
          100: 'rgb(var(--accent-tertiary-100))',
          200: 'rgb(var(--accent-tertiary-200))',
          300: 'rgb(var(--accent-tertiary-300))',
          400: 'rgb(var(--accent-tertiary-400))',
        },
        white: 'rgb(var(--white))',
        black: 'rgb(var(--black))',
        surface: {
          DEFAULT: 'rgb(var(--surface__surface))',
          primary: 'rgb(var(--surface__primary-container))',
          secondary: 'rgb(var(--surface__secondary-container))',
        },
      },
      fontFamily: {
        sans: ['var(--font-family-sans)'],
        'gt-haptik': ['var(--font-family-gt-haptik)'],
        'gt-haptik-rotalic': ['var(--font-family-gt-haptik-rotalic)'],
      },
      fontWeight: {
        lazer: '100',
        thin: '200',
        light: '300',
        normal: '400',
        medium: '500',
        bold: '700',
        black: '900',
      },
    },
  },
  plugins: [StatePlugin(), PartPlugin(), TypographyPlugin()],
} satisfies Config;
