apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  SENDGRID_API_KEY: {{ .Values.secrets.sendgridApiKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-session-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-postgresql-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
